In [ ]:
import requests
from requests.auth import HTTPBasicAuth
from bs4 import BeautifulSoup
import time
import pandas as pd
import numpy as np

In [ ]:
def get_url_paths(url, ext = ''):
   
    """
    Returns the full URL paths of all the files that have desired endings.
    
    :param url: The URL link from where the information should be imported.
    :param ext: The set of desired endings of the files.
    
    To return the output the function at first accesses and requests information from the server.
    When the request succeeded and the html of the server is ready, the function parses the hyml text to work easier.
    Then finds desired files and returns their full URL paths.
    
    """
    response = requests.get(url, verify = False)
    if response.ok:
        response_text = response.text
    else:
        return response.raise_for_status()
    soup = BeautifulSoup(response_text, 'html.parser')
    links = ['https://www.cba.am/' + node.get('href') for node in soup.find_all('a') if node.get('href').endswith(ext)]
    return links


def download():
    
    """
    For the given URLs the function calls get_url_paths function and downloads needed information in non-existing files.
    
    :param: None
    
    """
    
    urls = ['https://www.cba.am/en/SitePages/statrealsector.aspx',
            'https://www.cba.am/en/SitePages/statmonetaryfinancial.aspx', 
            'https://www.cba.am/en/SitePages/statexternalsector.aspx']
    ext = ('.xlsx', '.xls')
    for url in urls:
        paths = get_url_paths(url, ext)
        for path in paths:
            file_name = path[45:]
            information = requests.get(path, verify = False)
            if file_name.endswith('xls') is True:
                with open (f'C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\{file_name}.xls', 'wb') as file:
                    file.write(information.content)
            else:
                with open (f'C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\{file_name}.xlsx', 'wb') as file:
                    file.write(information.content)

In [ ]:
#To run the code change the path where the information should be downloaded.
time_start = time.time()
download()
time_end = time.time()
print("Elapsed time during the whole program in seconds:", time_end-time_start)

In [195]:
 #I SUGGEST CREATING A VARIABLE FOR FILE PATH AND USE THE VARIABLE EACH TIME BELOW INSTEAD OF REPEATING THE PATH ITSELF
def money_base():
    money_base_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\2-Money%20Base.xlsx.xlsx', 
                                 sheet_name = 'Money Base-table-actual', header = 3, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all')
    money_base_table = money_base_table_row.set_axis(pd.date_range(money_base_table_row.columns[0], periods=len(money_base_table_row.columns), freq="m"), axis='columns').transpose()
    return money_base_table

def broad_money():
    broad_money_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\3-Broad%20Money.xlsx.xlsx',
                                     sheet_name = 'Broad Money-actual', header = 3, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all')
    broad_money_table =  broad_money_table_row.set_axis(pd.date_range(broad_money_table_row.columns[0], periods=len(broad_money_table_row.columns), freq="m"), axis='columns').transpose()
    return broad_money_table

def aggregates():
    aggregates_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\4-Aggregates.xlsx.xlsx',
                              header = 3, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all')
    return aggregates_table

def deposits_sector():
    deposits_sector_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\5-Deposits%20by%20sectors.xlsx.xlsx',
                                sheet_name = 'deposits', header = 4, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all').transpose()
    return deposits_sector_table

def loans_sector():
    loans_sector_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\6-loans%20by%20sectors.xlsx.xlsx',
                                  sheet_name = 'loan Banks ', header = 4, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all').transpose()
    return loans_sector_table

def loans_branches():
    loans_branches_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\7-loans%20by%20branches.xlsx.xlsx',
                                    sheet_name = 'NACE breakdown COs', header = [3,4], index_col = 0).replace('None', np.nan).dropna(how = 'all').transpose()
    return loans_branches_table

def policy_rate():
    policy_rate_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\8-policy%20rates.xlsx.xlsx',
                                 header = 2, index_col = 'Time Period').replace('None', np.nan).dropna(how = 'all')
    return policy_rate_table

def fin_market():
    fin_market_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\9-fin%20market.xlsx.xlsx',
                                header = [3,4], index_col = 0).transpose()
    return fin_market_table

def eer():
    eer_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\10.%20EER.xlsx.xlsx',
                         header = 2, index_col = 'months').replace('None', np.nan).dropna(how = 'all').transpose()
    return eer_table

def bank_reference():
    bank_reference_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\10-bank%20reference%20rate.xlsx.xlsx',
                                    header = 3, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all')
    return bank_reference_table

def deposit_rate():
    deposit_rate_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\11-Deposit%20rates.xlsx.xlsx',
                                  header = [4,5], index_col = 0).replace('None', np.nan).dropna(how = 'all')
    return deposit_rate_table

def lending_rate():
    lending_rate_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\12-Lending%20rates.xlsx.xlsx',
                                  header = [3,4], index_col = 0).replace('None', np.nan).dropna(how = 'all')
    return lending_rate_table

def gov_security():
    gov_security_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\13-Gov.%20securities%20yield.xlsx.xlsx',
                                  header = [3,4], index_col = 0).replace('None', np.nan).dropna(how = 'all')
    return gov_security_table

def gdp():
    gdp2008_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\GDPexp.a.Eng_2008.xlsx.xlsx',
                             sheet_name = 'Volume indices', header = 2, index_col = 1).drop('Unnamed: 0', axis = 1).transpose()
    return gdp2008_table

def gdp_nace():
    gdp2008_NACE_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\GDPprod.q.Eng.NACE%202_2008.xlsx.xlsx',
                                  sheet_name = 'Chain-linked volume indices', header = 2, index_col = 1).drop('Unnamed: 0', axis = 1).transpose()
    gdp2008_NACE_table.index = pd.to_datetime(gdp2008_NACE_table.index).strftime('%Y-%m-%d')
    return gdp2008_NACE_table

def individual_transfer():
    transfer_individual_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\5.%20Money%20transfers%20of%20individuals.xls.xls',
                                         sheet_name = 'monthly', header = 3, index_col = 0).replace('None', np.nan).dropna(how = 'all')
    transfer_individual_table = transfer_individual_table_row.set_axis(pd.date_range(transfer_individual_table_row.columns[0], periods = len(transfer_individual_table_row.columns), freq = 'm'), axis = 'columns').transpose()
    return transfer_individual_table

def cpi():
    CPI_table_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\6.CPI.xls.xls', header = 3, index_col = 0).iloc[:-3].transpose()
    CPI_table_table_row =  CPI_table_table_row.set_axis(pd.date_range(CPI_table_table_row.columns[0], periods=len(CPI_table_table_row.columns), freq="m"), axis='columns').transpose().drop(['Unnamed: 5'], axis = 1)
    return CPI_table_table_row

def int_reserve():
    int_reserve_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\7.International%20reserves.xls.xls',
                                     header = 3, index_col = 'Unnamed: 0').replace('None', np.nan).dropna(how = 'all')
    int_reserve_table =  int_reserve_table_row.set_axis(pd.date_range(int_reserve_table_row.columns[0], periods=len(int_reserve_table_row.columns), freq="m"), axis='columns').transpose()
    return int_reserve_table

def rate():
    rates_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\8.%20Exchange%20rates.xls.xls', sheet_name = 'Monthly-average',
                           header = 2, index_col = 0).iloc[1:]
    rates_table[' IRR'] = (rates_table[' IRR']/100)
    return rates_table

def bop():
    bop_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\BOP_eng_for%20siteBPM6_rev.xls.xls', 
                          sheet_name = 'Quarterly', header = 3, index_col = 0).replace('None', np.nan).dropna(how = 'all')
    bop_table =  bop_table_row.set_axis(pd.date_range(bop_table_row.columns[0], periods=len(bop_table_row.columns), freq="q"), axis='columns').transpose()
    return bop_table

def exd():
    exd_table_row = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\ExD_eng_for%20site%20BPM6_rev.xls.xls', sheet_name = 'Quarterly',
                             header = 3, index_col = 0)
    exd_table_row =  exd_table_row.set_axis(pd.date_range(exd_table_row.columns[0], periods=len(exd_table_row.columns), freq="q"), axis='columns').transpose()
    return exd_table_row

def gdpnace_prod():
    gdp_nace_a_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\GDPprod.a.Eng%20NACE%202_2008.xls.xls', sheet_name = 'Volume indices',
                              header = 2, index_col = 1).drop(['Unnamed: 0'], axis = 1).transpose()
    return gdp_nace_a_table

def int_investment():
    int_investment_table = pd.read_excel('C:\\Users\\LENOVO\\Desktop\\Capstone\\Files\\IIP_eng_for%20site%20BPM6_rev.xls.xls', sheet_name = 'Quarterly',
                                    header = 2, index_col = 0)
    int_investment_table =  int_investment_table.set_axis(pd.date_range(int_investment_table.columns[0], periods=len(int_investment_table.columns), freq="q"), axis='columns').transpose()
    return int_investment_table



money_base = pd.melt(money_base.reset_index(), id_vars = 'index')
money_base.columns = ['Date','Indicator','Amount']
money_base.loc[:,'Table'] = 'Monetary base'
#THE SAME CODE SHOULD BE WRITTEN FOR BELOW TABLES AND AFTER THAT MAY BE CONCATENATED
broad_money = broad_money()
aggregates = aggregates()
deposits_sector = deposits_sector()
loans_sector = loans_sector()
loans_branches = loans_branches()
policy_rate = policy_rate()
fin_market = fin_market()
eer = eer()
bank_reference = bank_reference()
deposit_rate = deposit_rate()
lending_rate = lending_rate()
gov_security = gov_security()
gdp = gdp()
gdp_nace = gdp_nace()
individual_transfer = individual_transfer()
cpi = cpi()
int_reserve = int_reserve()
rate = rate()
bop = bop()
exd = exd()
gdpnace_prod = gdpnace_prod()
int_investment = int_investment()

data = pd.concat([money_base, broad_money, aggregates, deposits_sector, loans_sector, loans_branches, policy_rate, fin_market, eer,
          bank_reference, deposit_rate, lending_rate, gov_security, gdp, gdp_nace, individual_transfer, cpi,
          int_reserve, rate, bop, exd, gdpnace_prod, int_investment], axis = 1)

In [196]:
data

,NET INTERNATIONAL RESERVES 1,NET DOMESTIC ASSETS,Government,Banks,including Repo agreements,CBA foreign currency swap (FX attraction),Deposits (-),Reverse repo (-),CBA foreign currency swap (FX allocation) (-),Securities issued by the CBA (-),...,Central bank,"Deposit-taking corporations, except central bank",General government,Other sectors,Other accounts payable - other,Central bank,"Deposit-taking corporations, except the central bank",General government,Other sectors,Special drawing rights
2003-01-31,132878.880279,-32788.880279,-12931.000000,9642.0,0.0,0.0,-750.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-02-28,125198.660694,-27415.660694,-10362.000000,4981.0,0.0,0.0,-2360.0,-159.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-03-31,117276.143197,-23945.143197,-13564.000000,7500.0,0.0,0.0,0.0,0.0,0.0,NaN,...,0.044121,0.0,0.0,250.404778,80.949037,0.03343,0.401386,23.916177,56.598044,0.0
2003-04-30,132051.136670,-34721.136670,-23752.000000,7650.0,0.0,0.0,0.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-05-31,136217.909685,-35767.909685,-22789.606836,7500.0,0.0,0.0,-300.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN